version: '3.8'

services:
  mongo1:
    image: mongo:6.0
    container_name: mongo1
    restart: always
    ports:
      - 27017:27017
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]


  mongo2:
    image: mongo:6.0
    container_name: mongo2
    restart: always
    ports:
      - 27018:27017
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  mongo3:
    image: mongo:6.0
    container_name: mongo3
    restart: always
    ports:
      - 27019:27017
    networks:
      - mongo-cluster
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]

  spring-boot-app:
    image: nuhgnod/mongo-replicas-app:0.0.7
    container_name: spring-boot-container
    ports:
      - "8080:8080"
    depends_on:
      - mongo1
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge